drivers: soc: Remove an unused variable
../drivers/soc/qcom/glink_loopback_server.c:810:18: error: unused variable 'tx_done_ch_info' [-Werror,-Wunused-variable]
        struct ch_info *tx_done_ch_info = (struct ch_info *)priv;
                        ^
1 error generated.

Signed-off-by: MadeOfGreat <ravenklawasd@gmail.com>
Signed-off-by: CloudedQuartz <ravenklawasd@gmail.com>